// To Do/todo-vue/src/components/Header.vue
<template>
    <div class="today" id="today">
        <h1>{{ Day() }}</h1>
        <h3>{{ DateToday()}}</h3>
    </div>
</template>

<script>
    export default {
        name:'Header',
        data(){
            return{
            todayDate: new Date(),
            }
        },
        methods:{       
            Day(){ 
                const days = [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ];
    return days[this.todayDate.getDay()];
            },
            DateToday(){
      const months = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
        ];
    return `${
      months[this.todayDate.getMonth()]
    } ${this.todayDate.getDate()}, ${this.todayDate.getFullYear()}`;
            }
        }

    }
</script>

<style scoped>
.today {
  margin: 0.5rem 0;
  text-align: center;
}

</style>

// To Do/todo-app/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent implements OnInit {
  day: string;
  date: string;
  todaysDate: Date;
  constructor() {
    this.day = '';
    this.date = '';
    this.todaysDate = new Date();
  }
  ngOnInit(): void {}
  get Day() {
    const days = [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ];
    return days[this.todaysDate.getDay()];
  }
  get Date() {
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    return `${
      months[this.todaysDate.getMonth()]
    } ${this.todaysDate.getDate()}, ${this.todaysDate.getFullYear()}`;
  }
}

<div class="today">
  <h1>{{ Day }}</h1>
  <h3>{{ Date }}</h3>
</div>
